id: P005621
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:07:44.046263
source_metadata:
  id: bdr:W30422
  title: ཤེས་རིག་འཚོལ་བའི་གླེང་མོལ།
  author: ''
  volumes:
    832f5fbc7aa94b58ab34f4d775ccf992:
      image_group_id: I1KG23280
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
